spring:
  config:
    activate:
      on-profile: docker
  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
      repositories:
        enabled: false
  devtools:
    restart:
      enabled: false

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2s

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:pgsql}:${DATABASE_PORT:5432}/${DATABASE_NAME:adventure-library}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-migration-naming: true

logging:
  level:
    org.springframework.batch: INFO
    org.springframework.jdbc.core: INFO
    org.hibernate.SQL: OFF