spring:
  application:
    name: adventure-library

  messages:
    basename: messages
    encoding: UTF-8

  web:
    resources:
      add-mappings: false

  jpa:
    open-in-view: false
    properties:
      hibernate:
        JDBC:
          batch_size: ${BATCH_SIZE:50}
        order_inserts: true
        order_updates: true

server:
  port: ${PORT:8080}