@startuml
actor user as "Angular App"

box "API Layer" #LightBlue
participant "BookController" as controller <<(C,#ADD1B2)>>
end box

box "Application Layer" #LightGreen
participant "UpdateBookUseCase" as usecase <<(C,#ADD1B2)>>
end box

box "Persistence Layer" #LightCoral
participant "BookRepository" as bookRepo <<(I,#ADD1B2)>>
end box

database "PostgreSQL" as db #MediumBlue

note right user
PATCH /api/v1/books/{bookId}

{
  "title": "New title",
  "author": "New author",
  "difficulty": "New difficult level",
  "category": "New category"
}
end note

user -> controller : updateBook(bookId, request)
controller -> usecase : updateBook(bookId, request)

usecase -> bookRepo : findById(bookId)
bookRepo -> db : SELECT book
db --> bookRepo : BookEntity
bookRepo --> usecase : Book

usecase -> usecase : Apply partial updates

usecase -> bookRepo : save(book)
bookRepo -> db : UPDATE books
db --> bookRepo : updated
bookRepo --> usecase : Book

usecase --> controller : BookDetailsResponse
controller --> user : 200 OK

@enduml